homeswap/accounts/urls.py
from django.urls import path, include
from .views import (log_out, HomeView, ProfileView, ProfileEditView, delete_image,
                    ProfileDetailsFactory)

app_name = 'accounts'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('logout/', log_out, name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<str:form_name>', ProfileEditView.as_view(), name='profile_edit'),
    path('delete_image/<int:pk>', delete_image, name='delete_image'),
    path('profile/details/<str:form_name>', ProfileDetailsFactory.as_view(), name='profile_detail')
]

homeswap/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogPostCreateView, delete_blog, BlogPostUpdateView, CheckBlogPost

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogPostCreateView.as_view(), name='create_blog'),
    path('check/', CheckBlogPost.as_view(), name="check_blog"),
    path('delete/<int:pk>', delete_blog, name='delete_blog'),
    path('edit/<int:pk>', BlogPostUpdateView.as_view(), name='edit'),
]

homeswap/homeswap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', include('search.urls', namespace='search')),
    path('messaging/', include('messaging.urls', namespace='messaging')),
    path('support/', include('support.urls', namespace='support')),
    path('accounts/', include('allauth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serving static files in development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homeswap/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from .validators import validate_postal_code


from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class ValidateModel(models.Model):
    
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
    
    class Meta:
        
        abstract = True


class AppUser(AbstractUser):
    
    profile_photo = models.ImageField(upload_to='profile_photo', default='profile_photo/default.jpg')
    phone_number = PhoneNumberField(null=True, blank=True, region='DE')
    biography = models.TextField(null=True, blank=True)
    street = models.CharField(max_length=40, null=True, blank=True)
    location = models.CharField(max_length=40, null=True, blank=True)
    max_capacity = models.SmallIntegerField(null=True, blank=True)
    postal_code = models.CharField(max_length=10, null=True, blank=True)
    birthday_date = models.DateField(null=True, blank=True)
    
    def __str__(self) -> str:
        return self.username

    def clean(self):
        if self.street and len(self.street) > 40:
            raise ValidationError({'street': 'street can contain not more 40 letters.'})
        
        if self.location and len(self.location) > 40:
            raise ValidationError({'location': 'location can contain not more 40 letters.'})
        
        if self.postal_code:
            if len(self.postal_code) > 10:
                raise ValidationError({'postal_code': 'A postal code can contain a maximum of 10 characters.'})
            validate_postal_code(self.postal_code, 'Any country')
        
        # just for test
        # if self.phone_number and not self.phone_number.is_valid():
        #     raise ValidationError({'phone_number': 'Invalid phone number format.'})
        
        validate_postal_code(self.postal_code, 'Any country')
        
        super().clean()

class HomePhoto(ValidateModel):
    
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name='home_photos')
    image = models.ImageField(upload_to='home_photos', null=True, blank=True)
    photo_type = models.CharField(max_length=50, help_text="Type of the Photo, e.g., 'kitchen', 'living room'.")
    
    def __str__(self):
        return f"{self.user.username} - {self.photo_type}"

homeswap/accounts/forms.py
from django import forms
from django.forms import BaseFormSet, modelformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget

from .models import HomePhoto, AppUser
from typing import Any


def authenticate_user_or_email(user_or_email, password):

    user = authenticate(user= user_or_email, password=password)

    if user is None:
        try:
            username_by_email = User.objects.get(email=user_or_email)
            
            user = authenticate(user=username_by_email.username, password=password)
        except User.DoesNotExist:
            pass
        
    return user


class LoginForm(forms.Form):
    
    username_or_email = forms.CharField(label='Username or E-mail')
    password = forms.CharField(widget=forms.PasswordInput())
    
    def clean(self) -> dict[str, Any]:
        cleaned_data = super().clean()
        username = cleaned_data.get('username_or_email')
        password = cleaned_data.get('password')
        
        user = authenticate_user_or_email(username, password)
        
        if user is None:
            raise ValidationError('Invalid login credentials')
        
        self.user = user
        
        return cleaned_data


class RegistrationForm(UserCreationForm):
    
    class Meta:
        model = AppUser
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2',
        ]
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True


class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = AppUser
        fields = []
        labels = {
            'profile_photo': '',
        }
        widgets = {
            'postal_code': forms.NumberInput(attrs={'class': 'no-spinners'}),
            'phone_number': PhoneNumberInternationalFallbackWidget(attrs={'region':'DE'}),
        }

    def __init__(self, *args, **kwargs):
        
        self.field_name = kwargs.pop('field_name', None)
        super(ProfileForm, self).__init__(*args, **kwargs)
        if self.field_name:
            self.fields[self.field_name] = self.Meta.model._meta.get_field(self.field_name).formfield()
        else:
            self.fields['profile_photo'] = self.Meta.model._meta.get_field('profile_photo').formfield()
            
    def clean(self):
        cleaned_data = super().clean()
        field_value = cleaned_data.get(self.field_name)
        
        if self.field_name == 'max_capacity' and field_value is not None:
            if field_value < 1:
                self.add_error(self.field_name, "Max capacity must be at least 1.")
            elif field_value > 10:
                self.add_error(self.field_name, "Max capacity cannot exceed 10.")
        
        return cleaned_data
            
    def save(self, commit=True):
        instance = super(ProfileForm, self).save(commit=False)
        if self.cleaned_data.get(self.field_name):
            setattr(instance, self.field_name, self.cleaned_data[self.field_name])
        if commit:
            instance.save()
        return instance

class HomePhotoForm(forms.ModelForm):
    
    class Meta:
        model = HomePhoto
        fields = ['image', 'photo_type']

homeswap/accounts/views.py
from django.forms import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet, Q
from django.http import HttpRequest, JsonResponse, HttpResponseRedirect
from django.http.response import HttpResponse as HttpResponse, Http404
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.views.generic import TemplateView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.validators import validate_email

from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.sites.shortcuts import get_current_site

from allauth.account.forms import LoginForm, SignupForm
from allauth import app_settings as allauth_app_settings

from allauth.account import app_settings
from allauth.account.adapter import get_adapter
from allauth.account.forms import (
    AddEmailForm,
    ChangePasswordForm,
    ConfirmLoginCodeForm,
    LoginForm,
    ReauthenticateForm,
    RequestLoginCodeForm,
    ResetPasswordForm,
    ResetPasswordKeyForm,
    SetPasswordForm,
    SignupForm,
    UserTokenForm,
)
from allauth.account.internal import flows
from allauth.account.mixins import (
    AjaxCapableProcessFormViewMixin,
    CloseableSignupMixin,
    LogoutFunctionalityMixin,
    NextRedirectMixin,
    RedirectAuthenticatedUserMixin,
    _ajax_response,
)
from allauth.account.models import (
    EmailAddress,
    EmailConfirmation,
    get_emailconfirmation_model,
)
from allauth.account.reauthentication import resume_request
from allauth.account.utils import (
    complete_signup,
    perform_login,
    send_email_confirmation,
    sync_user_email_addresses,
    url_str_to_user_pk,
    user_display,
)
from allauth.core import ratelimit
from allauth.core.exceptions import ImmediateHttpResponse
from allauth.core.internal.httpkit import redirect
from allauth.decorators import rate_limit
from allauth.utils import get_form_class

from typing import Any
from .models import AppUser, HomePhoto
from .forms import RegistrationForm, ProfileForm, HomePhotoForm #HomePhotoFormSet
from blog.models import BlogPost
from blog.forms import BlogPostForm
from messaging.models import Room
from support.forms import DepositForm
from support.models import Deposit

from bs4 import BeautifulSoup
import re

def extract_error_message(errors):
    soup = BeautifulSoup(errors.as_ul(), "html.parser")
    return soup.get_text()


def get_or_none(model, *args, **kwargs):
    
    try:
        return model.objects.get(*args, **kwargs)
    except ObjectDoesNotExist:
        return None
    except model.DoesNotExist:
        return None


sensitive_post_parameters_m = method_decorator(
    sensitive_post_parameters("oldpassword", "password", "password1", "password2")
)


@method_decorator(rate_limit(action="signup"), name="dispatch")
class HomeView(
    RedirectAuthenticatedUserMixin,
    CloseableSignupMixin,
    NextRedirectMixin,
    AjaxCapableProcessFormViewMixin,
    FormView,
    ):
    template_name = "home.html"
    form_class = LoginForm  # Default to LoginForm
    signup_form_class = SignupForm

    @sensitive_post_parameters_m
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if allauth_app_settings.SOCIALACCOUNT_ONLY and request.method != "GET":
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs
    
    def get_form_class(self):
        return get_form_class(app_settings.FORMS, "login", self.form_class)

    def form_valid(self, form):
        if isinstance(form, self.signup_form_class):
            self.user, resp = form.try_save(self.request)
            if resp:
                return resp
            try:
                redirect_url = self.get_success_url()
                return complete_signup(
                    self.request,
                    self.user,
                    email_verification=None,
                    success_url=redirect_url,
                )
            except ImmediateHttpResponse as e:
                return e.response
        else:
            redirect_url = self.get_success_url()
            try:
                return form.login(self.request, redirect_url=redirect_url)
            except ImmediateHttpResponse as e:
                return e.response

    def get_context_data(self, **kwargs):
        ret = super().get_context_data(**kwargs)
        form = ret["form"]
        email = self.request.session.get("account_verified_email")
        if email:
            email_keys = ["email"]
            if app_settings.SIGNUP_EMAIL_ENTER_TWICE:
                email_keys.append("email2")
            for email_key in email_keys:
                form.fields[email_key].initial = email
        signup_url = None
        if not allauth_app_settings.SOCIALACCOUNT_ONLY:
            signup_url = self.passthrough_next_url(reverse("account_signup"))
        login_url = self.passthrough_next_url(reverse("account_login"))
        site = get_current_site(self.request)

        signup_form = SignupForm()
        reset_password_form = ResetPasswordForm()

        ret.update(
            {
                'signup_form': signup_form,
                'reset_password_form': reset_password_form,
                "signup_url": signup_url,
                "login_url": login_url,
                "site": site,
                "SOCIALACCOUNT_ENABLED": allauth_app_settings.SOCIALACCOUNT_ENABLED,
                "SOCIALACCOUNT_ONLY": allauth_app_settings.SOCIALACCOUNT_ONLY,
                "LOGIN_BY_CODE_ENABLED": app_settings.LOGIN_BY_CODE_ENABLED,
            }
        )
        if app_settings.LOGIN_BY_CODE_ENABLED:
            request_login_code_url = self.passthrough_next_url(
                reverse("account_request_login_code")
            )
            ret["request_login_code_url"] = request_login_code_url
        return ret

    def get_initial(self):
        initial = super().get_initial()
        email = self.request.GET.get("email")
        if email:
            try:
                validate_email(email)
            except ValidationError:
                return initial
            initial["email"] = email
            if app_settings.SIGNUP_EMAIL_ENTER_TWICE:
                initial["email2"] = email
        return initial

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        signup_form = self.signup_form_class(request.POST)

        if 'signup' in request.POST:
            if signup_form.is_valid():
                return self.form_valid(signup_form)
            else:
                return self.form_invalid(form=False, signup_form=signup_form)
        
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form, signup_form=False)

    def form_invalid(self, form, signup_form):
        context = self.get_context_data()
        context['signup_form'] = signup_form if signup_form else self.signup_form_class
        context['form'] = form if form else self.get_form_class()
        context['signin_errors'] = False
        context['signup_errors'] = False
        if 'signin' in self.request.POST:
            context['signin_errors'] = True
        elif 'signup' in self.request.POST:
            context['signup_errors'] = True
        return self.render_to_response(context)


def log_out(request):
    logout(request)
    return redirect(reverse('accounts:home'))


class ProfileView(DetailView):
    
    model = AppUser
    template_name = 'main/profile.html'
    context_object_name = 'profile'
    success_url = reverse_lazy('accounts:profile')
    
    def dispatch(self, request: HttpRequest, *args: reverse_lazy, **kwargs: reverse_lazy) -> HttpResponse:
        self.form_name = self.request.session.get('form_name', None)
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):
        if not self.request.user.is_authenticated:
            raise PermissionDenied("You must be logged in to upload photos.")
        current_photos_count = HomePhoto.objects.filter(user=self.request.user).count()
        max_photos = 10
        self.left_amount = max_photos-current_photos_count
        self.extra_forms = min(3, self.left_amount)
        return modelformset_factory(HomePhoto, HomePhotoForm, extra=self.extra_forms, max_num=max_photos, fields=['image', 'photo_type'])
    
    def get_object(self, queryset: QuerySet[reverse_lazy] | None = ...) -> Model:
        if self.request.user.is_authenticated:
            self.object = self.request.user
        else:
            raise Http404("User must be authenticated")
        return self.object
    
    def get_context_data(self, **kwargs: reverse_lazy) -> dict[str, Any]:
        if not hasattr(self, 'object'):
            self.get_object()
        context =  super().get_context_data(**kwargs)
        FormClass = self.get_form_class()
        if 'form' not in context:
            context['form'] = FormClass(queryset=HomePhoto.objects.none())
        
        self.form_name = self.request.session.get('form_name', None)
        
        photos = HomePhoto.objects.filter(user=self.request.user)
        individual_post = get_or_none(BlogPost, user=self.request.user)

homeswap/accounts/templates/partials/biography.html
{% if profile.biography %}
    <div class="profile-detail" id="edit-biography" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">{{ profile.biography }}</strong>
            <p class="label-text">Biography</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='biography' %}" hx-target="#edit-biography">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-biography" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">Biography</strong>
            <p class="label-text" style="color:indianred;">Please enter your biography.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='biography' %}" hx-target="#edit-biography">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}

homeswap/accounts/templates/partials/email.html
{% if profile.email %}
    <div class="profile-detail" id="edit-email" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">{{ profile.email }}</strong>
            <p class="label-text">E-mail address</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='email' %}" hx-target="#edit-email">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-email" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">E-mail address</strong>
            <p class="label-text" style="color:indianred;">Please enter your email.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='email' %}" hx-target="#edit-email">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}

homeswap/accounts/templates/partials/first_name.html
{% if profile.first_name %}
    <div class="profile-detail" id="edit-first_name"  hx-swap="outerHTML">
        <div>
            <strong class="profile-value">{{ profile.first_name }}</strong>
            <p class="label-text">First name</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='first_name' %}" hx-target="#edit-first_name">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-first_name">
        <div class="profile-info">
            <strong class="profile-value">First name</strong>
            <p class="label-text" style="color:indianred;">Please enter your first name.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='first_name' %}" hx-target="#edit-first_name">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}

homeswap/accounts/templates/partials/image_upload.html
<div style="background-color: white;">
    <h3>Add your home pictures</h3>
        <div class="container mt-4">
            <!-- Bootstrap Carousel -->
            <div id="imageCarousel" class="carousel slide">
                <!-- Carousel Items -->
                <div class="carousel-inner">
                    {% for photo in photos %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img src="{{ photo.image.url }}" class="d-block w-100" alt="{{ photo.photo_type }}">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ photo.photo_type }}</h5>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- Carousel Controls -->
                <button class="carousel-control-prev" type="button" data-bs-target="#imageCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#imageCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        
            <!-- Thumbnails -->
            <div class="row mt-3">
                {% for photo in photos %}
                <div class="col-2 image-thumbnail">
                    <img src="{{ photo.image.url }}" class="img-fluid" data-bs-target="#imageCarousel" data-bs-slide-to="{{ forloop.counter0 }}" alt="{{ photo.photo_type }}">
                    <button type='button' class="btn btn-danger delete-button" hx-post="{% url 'accounts:delete_image' pk=photo.pk %}" hx-target='#refresh'>Delete</button>
                </div>
                {% endfor %}
            </div>
        </div>
        <br>
        <form id='image-upload-form' method="post" enctype="multipart/form-data" hx-encoding="multipart/form-data" hx-post="{% url 'accounts:profile' %}" hx-target='#refresh'>
        {% csrf_token %}
        {{ form.management_form }}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-9">
                    <table class="table table-bordered table-light">
                        <p style="color: black;">You can upload a maximum 10 Photos. {{ left_amount }} remaining.</p>
                        {% if form.forms.0.photo_type.help_text %}
                            <div class="mb-2" style="text-align: right; margin-right: 180px;">
                                <small class="form-text text-muted">{{ form.forms.0.photo_type.help_text }}</small>
                            </div>
                        {% endif %}
                        {% for form in form.forms %}
                        <tr>
                            <td>
                                {{ form.image.label_tag }} {{ form.image }}
                                {% if form.image.errors %}
                                    {% for error in form.image.errors %}
                                        <div style="color: red;">{{ error }}</div>
                                    {% endfor %}
                                {% endif %}
                            </td>
                            <td>
                                {{ form.photo_type.label_tag }} {{ form.photo_type }}
                                {% if form.photo_type.errors %}
                                    {% for error in form.photo_type.errors %}
                                        <div style="color: red;">{{ error }}</div>
                                    {% endfor %}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% if extra_num %}
                        <div class="progress">
                            <div id="image-upload-progress-bar" class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <br>
                        <div class="d-flex justify-content-end" style="margin-top: 20px; margin-bottom: 20px;">
                            <input type="submit" value="Submit" class="btn btn-primary" role="button">
                        </div>
                    {% else %}
                        <div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    htmx.on('#image-upload-form', 'htmx:xhr:progress', function(evt) {
        var percent = (evt.detail.loaded / evt.detail.total) * 100;
        var progressBar = htmx.find('#image-upload-progress-bar');
        progressBar.style.width = percent + '%';
        progressBar.setAttribute('aria-valuenow', percent);
    });
</script>

homeswap/accounts/templates/partials/last_name.html
{% if profile.last_name %}
    <div class="profile-detail" id="edit-last_name" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">{{ profile.last_name }}</strong>
            <p class="label-text">Last name</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='last_name' %}" hx-target="#edit-last_name">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-last_name" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">Last name</strong>
            <p class="label-text" style="color:indianred;">Please enter your last name.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='last_name' %}" hx-target="#edit-last_name">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}

homeswap/accounts/templates/partials/location.html
{% if profile.location %}
    <div class="profile-detail" id="edit-location" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">{{ profile.location }}</strong>
            <p class="label-text">Location</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='location' %}" hx-target="#edit-location">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-location" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">Location</strong>
            <p class="label-text" style="color:indianred;">Please enter your location.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='location' %}" hx-target="#edit-location">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}

homeswap/accounts/templates/partials/max_capacity.html
{% if profile.max_capacity %}
    <div class="profile-detail" id="edit-max_capacity" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">{{ profile.max_capacity }}</strong>
            <p class="label-text">Max capacity of your home</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='max_capacity' %}" hx-target="#edit-max_capacity">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-max_capacity" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">Max capacity</strong>
            <p class="label-text" style="color:indianred;">Please enter the max capacity of your home.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='max_capacity' %}" hx-target="#edit-max_capacity">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}

homeswap/accounts/templates/partials/phone_number.html
{% if profile.phone_number %}
    <div class="profile-detail" id="edit-phone_number" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">{{ profile.phone_number }}</strong>
            <p class="label-text">Phone number</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='phone_number' %}" hx-target="#edit-phone_number">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-phone_number" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">Phone number</strong>
            <p class="label-text" style="color:indianred;">Please enter your phone number.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='phone_number' %}" hx-target="#edit-phone_number">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}

homeswap/accounts/templates/partials/postal_code.html
{% if profile.postal_code %}
    <div class="profile-detail" id="edit-postal_code" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">{{ profile.postal_code }}</strong>
            <p class="label-text">Postal code</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='postal_code' %}" hx-target="#edit-postal_code">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% else %}
    <div class="profile-detail" id="edit-postal_code" hx-swap="outerHTML">
        <div class="profile-info">
            <strong class="profile-value">Zip code</strong>
            <p class="label-text" style="color:indianred;">Please enter your zip code.</p>
        </div>
        <a href="#" hx-get="{% url 'accounts:profile_edit' form_name='postal_code' %}" hx-target="#edit-postal_code">
            <i class="bi bi-pen small-icon"></i>
        </a>
    </div>
{% endif %}