homeswap/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogPostCreateView, delete_blog, BlogPostUpdateView, CheckBlogPost

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogPostCreateView.as_view(), name='create_blog'),
    path('check/', CheckBlogPost.as_view(), name="check_blog"),
    path('delete/<int:pk>', delete_blog, name='delete_blog'),
    path('edit/<int:pk>', BlogPostUpdateView.as_view(), name='edit'),
]

homeswap/homeswap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', include('search.urls', namespace='search')),
    path('messaging/', include('messaging.urls', namespace='messaging')),
    path('support/', include('support.urls', namespace='support')),
    path('accounts/', include('allauth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serving static files in development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homeswap/support/urls.py
from django.urls import path
from .views import submit_support_request, deposit_view, update_payment_status, DepositPaymentSuccessView

app_name = 'support'

urlpatterns = [
    path('submit/', submit_support_request, name='submit_support_request'),
    # Add more URLs as needed
    path('deposit/<int:room_id>/', deposit_view, name='deposit_view'),
    path('update_payment_status/<int:deposit_id>/', update_payment_status, name='update_payment_status'),
    path('payment_success/<str:is_paid>/<int:target_user_id>/', DepositPaymentSuccessView.as_view(), name='success_payment')
]

homeswap/support/models.py
# support/models.py
from django.conf import settings
from django.db import models
from accounts.models import AppUser
from messaging.models import Room

class SupportRequest(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Support Request from {self.email}'


class Deposit(models.Model):
    sender_user = models.ForeignKey(AppUser, related_name='room_sender_deposit', on_delete=models.CASCADE)
    receiver_user = models.ForeignKey(AppUser,related_name='room_receiver_deposit', on_delete=models.CASCADE)
    room = room = models.ForeignKey(Room, related_name='chat_room_deposit', on_delete=models.CASCADE, null=True, blank=True)
    sender_amount = models.DecimalField(max_digits=10, decimal_places=2)
    receiver_amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid_by_sender = models.BooleanField(default=False)
    is_paid_by_receiver = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.amount} - {'Paid' if self.is_paid else 'Pending'}"

    @property
    def is_paid(self):
        return self.is_paid_by_sender  and self.is_paid_by_receiver
    
    @property
    def is_pending(self):
        return self.is_paid_by_sender or self.is_paid_by_receiver

homeswap/support/forms.py
# messaging/forms.py

from django import forms
from .models import SupportRequest
from .models import Deposit

class SupportForm(forms.ModelForm):
    class Meta:
        model = SupportRequest
        fields = ['email', 'subject', 'message']

class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = []
    
    def __init__(self, *args, **kwargs):
        self.field_name = kwargs.pop('field_name', None)
        super(DepositForm, self).__init__(*args, **kwargs)
        if self.field_name:
            self.fields[self.field_name] = self.Meta.model._meta.get_field(self.field_name).formfield()

homeswap/support/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import SupportForm, DepositForm
from messaging.models import Room
from .models import Deposit
from blog.models import BlogPost
from accounts.models import AppUser

def submit_support_request(request):
    if request.method == 'POST':
        form = SupportForm(request.POST)
        if form.is_valid():
            # Process the support request
            # For example, save the support request to the database
            form.save()

            # Send a response email to the user
            user_email = form.cleaned_data['email']  # Assuming 'email' is the field for user's email address
            send_support_response_email(user_email)

            # Optionally, you can display a success message or redirect the user to a thank you page
            return render(request, 'support/thank_you.html')
    else:
        form = SupportForm()

    return render(request, 'support/submit_support_request.html', {'form': form})


def send_support_response_email(user_email):
    # Define the email subject and message
    subject = 'Thank you for your support request'
    message = 'We have received your support request and will respond as soon as possible.'

    # Set the sender email address
    sender_email = settings.EMAIL_HOST_USER  # Use the email address specified in settings

    # Send the email
    send_mail(subject, message, sender_email, [user_email])


@login_required
def deposit_view(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    deposit = get_object_or_404(Deposit, room=room)
    if request.method == 'POST':
        form = DepositForm(request.POST, instance=deposit)
        if form.is_valid():
            deposit = form.save()
            return redirect('support:update_payment_status', deposit_id=deposit.id)
    else:
        form = DepositForm(instance=deposit)
    
    return render(request, 'main/deposit.html', {'form': form, 'room': room})

@login_required
def update_payment_status(request, deposit_id):
    deposit = get_object_or_404(Deposit, id=deposit_id)
    target_user = None
    
    if request.user == deposit.sender_user:
        deposit.is_paid_by_sender = True
        target_user = deposit.receiver_user
    elif request.user == deposit.receiver_user:
        deposit.is_paid_by_receiver = True
        target_user = deposit.sender_user
    
    deposit.save()
    
    is_paid = 'false'
    
    if deposit.is_paid:
        is_paid = 'true'
        send_system_message_to_chat(deposit.room, "Both users have successfully paid the deposit.")
        return redirect('support:success_payment', is_paid=is_paid, target_user_id=target_user.id)
    
    return redirect('support:success_payment', is_paid=is_paid, target_user_id=target_user.id)


class DepositPaymentSuccessView(LoginRequiredMixin,TemplateView):
    def dispatch(self, request, *args, **kwargs):
        self.is_paid = kwargs.get('is_paid', 'false')
        self.target_user_id = kwargs.get('target_user_id', None)
        return super().dispatch(request, *args, **kwargs)
    def get_template_names(self) -> list[str]:
        if self.is_paid == 'true':
            
            return 'main/is_paid.html'
        return 'main/pending.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        
        if self.is_paid == 'true':
            is_paid = True
        else:
            is_paid = False
        
        target_user = get_object_or_404(AppUser, pk=self.target_user_id)
        target_user_blog = get_object_or_404(BlogPost, user=target_user)
        context['target_user_blog'] = target_user_blog
        context['is_paid'] = is_paid
        context['object_user'] = target_user.username
        return context


def send_system_message_to_chat(room, message):
    from channels.layers import get_channel_layer
    from asgiref.sync import async_to_sync
    from django.conf import settings
    from messaging.models import Message
    from accounts.models import AppUser

    channel_layer = get_channel_layer()
    system_user_id = settings.SYSTEM_USER_ID  
    system_user = AppUser.objects.get(id=system_user_id)
    
    room_group_name = f'chat_{room.room_name}'
    
    system_message = Message.objects.create(
        sender_user=system_user,
        receiver_user=room.receiver_user if room.sender_user == system_user else room.sender_user,
        room=room,
        message=message
    )
    system_message.save()
    
    async_to_sync(channel_layer.group_send)(
        room_group_name,
        {
            'type': 'chat_message',
            'message': message,
            'sender_name': 'System'
        }
    )

homeswap/support/templates/main/deposit.html
{% load account_tag %}
<div id="confirm-deposit" style="background-color: #18465a;">
    <br>
    <h3 style="color: white !important;">You are about to enter into a home swap with <strong>{{ object_user }}</strong> <img src="{{ object_user.profile_photo.url }}" class="img-thumbnail rounded-circle img-small"></h3>
    <h5 style="color: red; margin-left: 50px;">As a final step, you should charge the deposit. When both users have paid the deposit, you will receive a message in the chat.</h6>
        <br><br>
        <div class="container d-flex flex-column align-items-center">
            <div class="w-100 text-start mb-3" style="padding-left: 320px;">
                <p style="color: white;">Blog post by {{ object_user }}</p>
            </div>
            <div class="card mb-3" style="width: 40rem;">
                <div class="card-header">
                    <h4 class="card-title">{{ target_user_blog.title }}</h4>
                </div>
                <div class="card-body">
                    <div class="col-md-12 mb-4">
                        <div class="row">
                            <p class="card-text col-sm-2 mb-4">From:</p> <strong class="col-md-4 mb-4">{{ target_user_blog.user.location }}</strong> <p class="card-text col-md-2 mb-4">To:</p> <strong class="card-text col-md-4 mb-4">{{ target_user_blog.to_city }}</strong>
                        </div>
                        <div class="row">
                            <p class="card-text col-sm-2 mb-4">Departure:</p> <strong class="col-md-4 mb-4">{{ target_user_blog.start_date }}</strong>  <p class="card-text col-md-2 mb-4">End:</p> <strong class="card-text col-md-4 mb-4">{{ target_user_blog.end_date }}</strong>
                        </div>
                        <div class="row">
                            <p class="card-text col-sm-3 mb-4">Number of travelers:</p> <strong class="col-md-9 mb-4">{{ target_user_blog.num_travelers }}</strong>
                        </div>
                    </div>
                    <div class="col-md-12 mb-4">
                        <div>
                            <div>
                                <p class="card-text">Description:</p>
                            </div> 
                            <div class="custom-description">
                                <p class="card-text" style="color: white;">{{ target_user_blog.description }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <form method="post" hx-post="{% url 'support:deposit_view' room_id=is_confirmed.pk %}" hx-target="#confirm-deposit">
        {% csrf_token %}
        <div class="row" style="margin-top: 60px;">
            <div class="col-md-4 mb-4">
            </div>
            {% for field in deposit_form %}
                <div class="col-md-4 mb-4">
                    <p style="color: white;">Please enter the deposit amount:</p>{{ field|add_class:'form-control' }}
                    <br>
                    <div class="d-flex justify-content-end mt-3">
                        <button type="submit" class="btn btn-primary" stlye="margin-left: 500px">Submit</button>
                    </div>
                </div>
            {% endfor %}
            <div class="col-md-4 mb-4">
            </div>
        </div>
    </form>
    <br>
</div>

homeswap/support/templates/main/is_paid.html
<div id="confirm-deposit" style="background-color: #18465a;">
    <br>
    <h3 style="color: white !important;">Both users have paid. We wish you a nice trip!</h3>
        <br><br>
        <div class="container d-flex flex-column align-items-center">
            <div class="w-100 text-start mb-3" style="padding-left: 320px;">
                <p style="color: white;">Blog post by {{ object_user }}</p>
            </div>
            <div class="card mb-3" style="width: 40rem;">
                <div class="card-header">
                    <h4 class="card-title">{{ target_user_blog.title }}</h4>
                </div>
                <div class="card-body">
                    <div class="col-md-12 mb-4">
                        <div class="row">
                            <p class="card-text col-sm-2 mb-4">From:</p> <strong class="col-md-4 mb-4">{{ target_user_blog.user.location }}</strong> <p class="card-text col-md-2 mb-4">To:</p> <strong class="card-text col-md-4 mb-4">{{ target_user_blog.to_city }}</strong>
                        </div>
                        <div class="row">
                            <p class="card-text col-sm-2 mb-4">Departure:</p> <strong class="col-md-4 mb-4">{{ target_user_blog.start_date }}</strong>  <p class="card-text col-md-2 mb-4">End:</p> <strong class="card-text col-md-4 mb-4">{{ target_user_blog.end_date }}</strong>
                        </div>
                        <div class="row">
                            <p class="card-text col-sm-3 mb-4">Number of travelers:</p> <strong class="col-md-9 mb-4">{{ target_user_blog.num_travelers }}</strong>
                        </div>
                    </div>
                    <div class="col-md-12 mb-4">
                        <div>
                            <div>
                                <p class="card-text">Description:</p>
                            </div> 
                            <div class="custom-description">
                                <p class="card-text" style="color: white;">{{ target_user_blog.description }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <br><br>
</div>

homeswap/support/templates/main/pending.html
<div class="container d-flex align-items-center justify-content-center" id="confirm-deposit" style="background-color: #18465a; height: 400px;">
    <h5 class="text-white text-center">
        You have paid the deposit. Please wait until <strong>{{ object_user }}</strong> has paid. Once both users have paid, you will receive a message in the chat.
    </h5>
</div>