homeswap/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogPostCreateView, delete_blog, BlogPostUpdateView, CheckBlogPost

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogPostCreateView.as_view(), name='create_blog'),
    path('check/', CheckBlogPost.as_view(), name="check_blog"),
    path('delete/<int:pk>', delete_blog, name='delete_blog'),
    path('edit/<int:pk>', BlogPostUpdateView.as_view(), name='edit'),
]

homeswap/homeswap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', include('search.urls', namespace='search')),
    path('messaging/', include('messaging.urls', namespace='messaging')),
    path('support/', include('support.urls', namespace='support')),
    path('accounts/', include('allauth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serving static files in development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homeswap/search/urls.py
from django.urls import path
from .views import search_view, search_form_view, blog_post_details_view, api_search_blog_posts_view

app_name = 'search'

urlpatterns = [
    path('api/search/', search_view, name='search'),
    path('form/', search_form_view, name='search_form'),
    path('api/blog/<int:post_id>/', blog_post_details_view, name='blog_post_details'),
    path('api/search/blog-posts/', api_search_blog_posts_view, name='api_search_blog_posts'),
]

homeswap/search/models.py
from django.db import models

# Create your models here.

homeswap/search/forms.py
from django import forms

class BlogPostSearchForm(forms.Form):
    search_destination = forms.CharField(max_length=100, required=True)
    search_start_date = forms.DateField(required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    search_end_date = forms.DateField(required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    search_num_travelers = forms.IntegerField(min_value=1, required=True)

homeswap/search/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .serializers import BlogPostSerializer, HomePhotoSerializer
from blog.models import BlogPost
from accounts.models import AppUser, HomePhoto
from datetime import datetime
from .forms import BlogPostSearchForm
from django.db.models import Q

def search_form_view(request):
    form = BlogPostSearchForm()
    return render(request, 'search/search_form.html', {'form': form, 'blog_posts': None})

def search_view(request):
    blog_posts = None
    if request.method == 'GET' and 'search_destination' in request.GET:
        form = BlogPostSearchForm(request.GET)
        if form.is_valid():
            if request.user.is_authenticated:
                user_location = request.user.location

                search_destination = form.cleaned_data['search_destination']
                search_start_date = form.cleaned_data['search_start_date']
                search_end_date = form.cleaned_data['search_end_date']
                search_num_travelers = form.cleaned_data['search_num_travelers']
                
                blog_posts = BlogPost.objects.filter(
                    Q(to_city=user_location) &
                    Q(location=search_destination) &
                    Q(start_date__lte=search_start_date) &
                    Q(end_date__gte=search_end_date) &
                    Q(max_capacity__gte=search_num_travelers))
            else:
                return render(request, 'search/search_form.html', {
                    'form': form,
                    'error_message': 'Authentication credentials were not provided.',
                    'blog_posts': None,
                })
        else:
            form = BlogPostSearchForm()
    else:
        form = BlogPostSearchForm()
    
    print(blog_posts)
    return render(request, 'blog/blog_post_search_list.html', {'form': form, 'blog_posts': blog_posts})
    # return render(request, 'search/search_form.html', {'form': form, 'blog_posts': blog_posts})


@api_view(['GET'])
def blog_post_details_view(request, post_id):
    blog_post = get_object_or_404(BlogPost, id=post_id)
    user_photos = HomePhoto.objects.filter(user=blog_post.user)

    print("User Photos:", user_photos)  # Debug statement to check user_photos

    context = {
        'blog_post': blog_post,
        'user_photos': user_photos
    }

    return render(request, 'search/blog_post_details.html', context)


@api_view(['GET'])
def api_search_blog_posts_view(request):
    if request.method == 'GET' and 'search_destination' in request.GET:
        form = BlogPostSearchForm(request.GET)
        if form.is_valid():
            if request.user.is_authenticated:
                user_location = request.user.location

                search_destination = form.cleaned_data['search_destination']
                search_start_date = form.cleaned_data['search_start_date']
                search_end_date = form.cleaned_data['search_end_date']
                search_num_travelers = form.cleaned_data['search_num_travelers']
                
                blog_posts = BlogPost.objects.filter(
                    Q(to_city=user_location) &
                    Q(location=search_destination) &
                    Q(start_date__gte=search_start_date) &
                    Q(end_date__lte=search_end_date) &
                    Q(max_capacity__gte=search_num_travelers)
                )

                serializer = BlogPostSerializer(blog_posts, many=True)
                return Response(serializer.data, status=status.HTTP_200_OK)
            else:
                return Response({'error': 'Authentication credentials were not provided.'}, status=status.HTTP_401_UNAUTHORIZED)
        else:
            return Response(form.errors, status=status.HTTP_400_BAD_REQUEST)
    return Response({'error': 'Invalid request method or missing search parameters.'}, status=status.HTTP_400_BAD_REQUEST)

homeswap/search/templates/search/blog_post_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Post Details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <section id="details" class="details">
        <h1>Blog Post Details</h1>
        <article class="blognpic">
            <div id="blogPostDetails" class="blogPostDetails">
                <h2>Title: {{ blog_post.title }}</h2>
                <p>Description: {{ blog_post.description }}</p>
                <p>Location: {{ blog_post.location }}</p>
                <p>To City: {{ blog_post.to_city }}</p>
                <p>Max Capacity: {{ blog_post.max_capacity }}</p>
                <p>Start Date: {{ blog_post.start_date }}</p>
                <p>End Date: {{ blog_post.end_date }}</p>
            </div>

            <div id="userPhotos" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% for photo in user_photos %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img src="{{ photo.image.url }}" class="d-block w-100" alt="{{ photo.photo_type }}">
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#userPhotos" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#userPhotos" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </article>
    </section>
</body>
</html>

homeswap/search/templates/search/search_form.html
{% load static %}
{% load account_tag %}
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
        Search
    </button>
    <div class="dropdown-menu dropdown-menu-dark p-3" style="min-width: 300px;">
        <section class="search">
            <h4 class="dropdown-header text-white custom-header">Search Blog Posts</h4>
            <div class="dropdown-body">
                <form action="{% url 'search:search' %}" method="GET" class="search-form">
                    <div class="mb-3">
                        {% for field in form %}
                            <div class="mb-2">
                                <label for="{{ field.id_for_label }}" class="form-label text-white">{{ field.label }}</label>
                                {{ field|add_class:'form-control' }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="text-end">
                        <button type="submit" class="btn btn-light">Search</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>


{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Blog Posts</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <section class="search">
        <h1>Search Blog Posts</h1>
        <form action="{% url 'search:search' %}" method="GET" class="search-form">
            {{ form.as_p }}
            <button type="submit">Search</button>
        </form>

        {% if blog_posts is not None %}
            <div id="searchResults">
                {% if blog_posts %}
                    {% for post in blog_posts %}
                    <a href="{% url 'search:blog_post_details' post.id %}" target="_blank">
                            <div class="search-result">
                                <h2>Title: {{ post.title }}</h2>
                                <p>Location: {{ post.location }}</p>
                                <p>To City: {{ post.to_city }}</p>
                                <p>Max Capacity: {{ post.max_capacity }}</p>
                                <p>Start Date: {{ post.start_date }}</p>
                                <p>End Date: {{ post.end_date }}</p>
                            </div>
                        </a>
                    {% endfor %}
                {% else %}
                    <p>No results found.</p>
                {% endif %}
            </div>
        {% endif %}
    </section>
</body>
</html> {% endcomment %}