homeswap/accounts/urls.py
from django.urls import path, include
from .views import (log_out, HomeView, ProfileView, ProfileEditView, delete_image,
                    ProfileDetailsFactory)

app_name = 'accounts'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('logout/', log_out, name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<str:form_name>', ProfileEditView.as_view(), name='profile_edit'),
    path('delete_image/<int:pk>', delete_image, name='delete_image'),
    path('profile/details/<str:form_name>', ProfileDetailsFactory.as_view(), name='profile_detail')
]

homeswap/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogPostCreateView, delete_blog, BlogPostUpdateView, CheckBlogPost

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogPostCreateView.as_view(), name='create_blog'),
    path('check/', CheckBlogPost.as_view(), name="check_blog"),
    path('delete/<int:pk>', delete_blog, name='delete_blog'),
    path('edit/<int:pk>', BlogPostUpdateView.as_view(), name='edit'),
]

homeswap/homeswap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', include('search.urls', namespace='search')),
    path('messaging/', include('messaging.urls', namespace='messaging')),
    path('support/', include('support.urls', namespace='support')),
    path('accounts/', include('allauth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serving static files in development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homeswap/blog/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError

from accounts.models import AppUser
import datetime as dt

class BlogPost(models.Model):
    title = models.CharField(max_length=100, default='Untitled')
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name='blog_by_user')
    location = models.CharField(max_length=100)
    max_capacity = models.PositiveIntegerField()
    to_city = models.CharField(max_length=100)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField()
    num_travelers = models.PositiveIntegerField(default=1)
    description = models.TextField()
    created_date = models.DateField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)

    def clean(self) -> None:
        
        if self.start_date < dt.date.today():
            raise ValidationError({'start_date': "Start date can't be older then today"})
        
        if self.end_date and self.end_date < dt.date.today():
            raise ValidationError({'end_date': "End date can't be older then today"})
        
        if self.num_travelers < 1:
            raise ValidationError({'num_travelers': "Number of travelers needs to be at least 1."})
        
        super().clean()

homeswap/blog/forms.py
from django import forms
from .models import BlogPost
from django.utils.dateparse import parse_date
import datetime


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'to_city', 'start_date', 'end_date', 'num_travelers', 'description', 'max_capacity']
        
    start_date = forms.DateField(
        label='Start Date',
        widget=forms.DateInput(
            attrs={
                'type':"date",
            }
        ))
    end_date = forms.DateField(
        label='End Date',
        widget=forms.DateInput(
            attrs={
                'type':"date",
            }
        ))
    
    num_travelers = forms.IntegerField(
        label='Number of travelers'
    )
    
    max_capacity = forms.IntegerField(disabled=True)
    location = forms.CharField(disabled=True)
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(BlogPostForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['location'].initial = user.location
            self.fields['max_capacity'].initial = user.max_capacity

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        location = cleaned_data.get("location")
        max_capacity = cleaned_data.get("max_capacity")
        num_travelers = cleaned_data.get("num_travelers")

        if start_date and end_date and start_date >= end_date:
            self.add_error('end_date', "End date must be after start date.")

        if not location:
            self.add_error('location', "You need to fill in your location on your profile to post.")

        if not max_capacity:
            self.add_error('max_capacity', "You need to fill in the max capacity of your home on your profile to post.")
        
        if num_travelers <= 0:
            self.add_error('num_travelers', "Number of travelers need to be at least 1.")
        
        return cleaned_data

homeswap/blog/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView, ListView, TemplateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.views.generic.edit import UpdateView
from django.http import Http404
from django.core.paginator import Paginator

from typing import Any
from .forms import BlogPostForm
from .models import BlogPost
from accounts.models import HomePhoto
from accounts.views import get_or_none
from search.forms import BlogPostSearchForm


class BlogListView(ListView):
    
    model = BlogPost
    template_name = 'blog_post_list.html'
    context_object_name = 'blog_posts'
    
    def dispatch(self, request: HttpRequest, *args: reverse_lazy, **kwargs: reverse_lazy) -> HttpResponse:
        self.page_number = request.GET.get('page', 1)
        
        return super().dispatch(request, *args, **kwargs)
    
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        
        queryset = BlogPost.objects.all()
        
        return queryset
    
    def get_context_data(self, **kwargs: reverse_lazy) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['form'] = BlogPostSearchForm()
        number_of_items = 5
        
        paginator = Paginator(self.get_object(), number_of_items)
        page_obj = paginator.get_page(self.page_number)
        
        context['page_obj'] = page_obj
        
        return context


class BlogPostCreateView(FormView):
    
    template_name = 'create_blog_post.html'
    form_class = BlogPostForm
    success_url = reverse_lazy('blog:check_blog')
    
    def get_context_data(self, **kwargs: reverse_lazy) -> dict[str, Any]:
        
        if self.request.user.is_authenticated:
            context = super().get_context_data(**kwargs)
            
            photos = HomePhoto.objects.filter(user=self.request.user)
            
            context['photos'] = photos
            
            return context
        else:
            raise PermissionDenied("You must be logged in.")
    
    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
        
    def form_valid(self, form):
        blog_post = form.save(commit=False)
        blog_post.user = self.request.user
        blog_post.location = self.request.user.location
        blog_post.max_capacity = self.request.user.max_capacity
        blog_post.save()
        return super().form_valid(form)


def delete_blog(request, pk):
    if request.method == 'POST' and request.user.is_authenticated:
        
        delete_obj = get_object_or_404(BlogPost, pk=pk, user=request.user)
        delete_obj.delete()
        return redirect('accounts:profile')
    else:
        raise HttpResponse("Invalid request", status=400)


class CheckBlogPost(TemplateView):
    template_name = "partials/check_individual_post.html"

    def get_context_data(self, **kwargs: reverse_lazy) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        individual_post = get_or_none(BlogPost, user=self.request.user)
        context['individual_post'] = individual_post
        return context


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = "partials/blogpost_update.html"
    success_url = reverse_lazy('blog:check_blog')

    def dispatch(self, request, *args, **kwargs):
        self.pk = kwargs.get('pk', None)
        return super().dispatch(request, *args, **kwargs)
    
    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        
        obj = super().get_object(queryset)
        
        if obj.user != self.request.user:
            raise Http404("You do not have permission to access this object")
        return obj

    def get_queryset(self):
        return BlogPost.objects.filter(pk=self.pk)

    def get_context_data(self, **kwargs: reverse_lazy) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['pk'] = self.pk
        return context

homeswap/blog/templates/partials/blogpost_in_profile.html
<div id='display-individual-post' class="blog-post-in-profile">
    {% if individual_post %}
    <h3>Please check your blog post</h3>
    <div class="container d-flex flex-column align-items-center">
        <div class="card mb-3" style="width: 40rem;">
            <div class="card-body">
                <div class="col-md-12 mb-4">
                    <div class="row">
                        <p class="card-text col-sm-2 mb-4">From:</p> <strong class="col-md-4 mb-4">{{ individual_post.user.location }}</strong> <p class="card-text col-md-2 mb-4">To:</p> <strong class="card-text col-md-4 mb-4">{{ individual_post.to_city }}</strong>
                    </div>
                    <div class="row">
                        <p class="card-text col-sm-2 mb-4">Departure:</p> <strong class="col-md-4 mb-4">{{ individual_post.start_date }}</strong>  <p class="card-text col-md-2 mb-4">End:</p> <strong class="card-text col-md-4 mb-4">{{ individual_post.end_date }}</strong>
                    </div>
                    <div class="row">
                        <p class="card-text col-sm-3 mb-4">Number of travelers:</p> <strong class="col-md-9 mb-4">{{ individual_post.num_travelers }}</strong>
                    </div>
                </div>
                <div class="col-md-12 mb-4">
                    <div>
                        <div>
                            <p class="card-text">Description:</p>
                        </div> 
                        <div class="custom-description">
                            <p class="card-text" style="color: white;">{{ individual_post.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end">
                <a class="btn btn-primary" href="{% url 'blog:home' %}" role="button">Go to the blog</a>
                <a class="btn btn-info" role="button" style="margin-left: 5px;">Edit</a>
                <a class="btn btn-danger" href="#" hx-post="{% url 'blog:delete_blog' pk=individual_post.pk %}" hx-target='#refresh' role="button" style="margin-left: 5px;">Delete</a>
        </div>
    <div>
    {% else %}
    <h3>Create your blog post to find a home swap</h3>
    <p style="color: black; margin-left: 700px;">You haven't created your blog post yet. <a class="btn btn-light blog-display-button" href='#' hx-get="{% url 'blog:create_blog' %}" hx-target="#display-individual-post" role="button">Click</a> here to create one or explore the <a class="btn btn-success blog-display-button" href="{% url 'blog:home' %}" role="button">blog</a></p>
    {% endif %}
    <br>
</div>

homeswap/blog/templates/partials/blogpost_update.html
{% load account_tag %}
<div id="blog-update" class="container">
    <h3>Edit your blog post</h3>
    <div class="row justify-content-center">
        <div class="col-md-5">
            <form method="POST" hx-post="{% url 'blog:edit' pk=pk %}" hx-target="#blog-update">
                    {% if form.location.errors or form.max_capacity.errors %}
                        {% for error in form.location.errors %}
                                {% if error != 'This field is required.' %}
                                <div class="alert alert-danger">
                                    {{ error }}
                                </div>
                                {% endif %}
                        {% endfor %}
                        {% for error in form.max_capacity.errors %}
                            {% if error != 'This field is required.' %}
                            <div class="alert alert-danger">
                                {{ error }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'location' and field.name != 'max_capacity' %}
                            <label for="{{ field.id_for_label }}" style="color: dimgrey;">{{ field.label }}</label>
                        <div class="mb-3">
                            {{ field|add_class:'form-control' }}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="d-flex justify-content-end">
                    <button class="btn btn-primary create_blog_post_button"  style="margin-top: 20px; margin-bottom: 20px;" type="submit">Submit</button>
                    <a href='#' hx-get='{% url "accounts:profile" %}' hx-target='#refresh' class="btn btn-warning create_blog_post_button"  style="margin-top: 20px; margin-bottom: 20px;" role="button">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

homeswap/blog/templates/partials/check_individual_post.html
<div id='display-individual-post' class="blog-post-in-profile">
<div id='edit-individual-post'>
    {% if individual_post %}
    <h3>Please check your blog post</h3>
    <div class="container d-flex flex-column align-items-center">
        <div class="card mb-3" style="width: 40rem;">
            <div class="card-header">
                <h4 class="card-title">{{ individual_post.title }}</h4>
            </div>
            <div class="card-body">
                <div class="col-md-12 mb-4">
                    <div class="row">
                        <p class="card-text col-sm-2 mb-4">From:</p> <strong class="col-md-4 mb-4">{{ individual_post.user.location }}</strong> <p class="card-text col-md-2 mb-4">To:</p> <strong class="card-text col-md-4 mb-4">{{ individual_post.to_city }}</strong>
                    </div>
                    <div class="row">
                        <p class="card-text col-sm-2 mb-4">Departure:</p> <strong class="col-md-4 mb-4">{{ individual_post.start_date }}</strong>  <p class="card-text col-md-2 mb-4">End:</p> <strong class="card-text col-md-4 mb-4">{{ individual_post.end_date }}</strong>
                    </div>
                    <div class="row">
                        <p class="card-text col-sm-3 mb-4">Number of travelers:</p> <strong class="col-md-9 mb-4">{{ individual_post.num_travelers }}</strong>
                    </div>
                </div>
                <div class="col-md-12 mb-4">
                    <div>
                        <div>
                            <p class="card-text">Description:</p>
                        </div> 
                        <div class="custom-description">
                            <p class="card-text" style="color: white;">{{ individual_post.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end">
                <a class="btn btn-primary" href="{% url 'blog:home' %}" role="button">Go to the blog</a>
                <a class="btn btn-info" href="#" hx-get="{% url 'blog:edit' pk=individual_post.pk %}" hx-target='#edit-individual-post' role="button" style="margin-left: 5px;">Edit</a>
                <a class="btn btn-danger" href="#" hx-post="{% url 'blog:delete_blog' pk=individual_post.pk %}" hx-target='#refresh' role="button" style="margin-left: 5px;">Delete</a>
        </div>
    <div>
    {% else %}
    <h3>Create your blog post to find a home swap</h3>
    <p style="color: black; margin-left: 700px;">You haven't created your blog post yet. <a class="btn btn-light blog-display-button" href='#' hx-get="{% url 'blog:create_blog' %}" hx-target="#display-individual-post" role="button">Click</a> here to create one or explore the <a class="btn btn-success blog-display-button" href="{% url 'blog:home' %}" role="button">blog</a></p>
    {% endif %}
    <br>
</div>
</div>